#!/usr/bin/env python3
"""Stable multi-hop route projection for a modular consumer repository."""
from __future__ import annotations

from pathlib import Path

from consumer_bootstrap_common import BootstrapError, WORKFLOW_ADAPTER

BEGIN = "<!-- BEGIN DOMAIN DECOUPLING BOOTSTRAP -->"
END = "<!-- END DOMAIN DECOUPLING BOOTSTRAP -->"
WORKFLOW_MARKER = "# GENERATED BY DOMAIN-DECOUPLING-V1 CONSUMER BOOTSTRAP"

DOC_ROUTES = (
    Path("README.md"), Path("AGENTS.md"), Path("CLAUDE.md"), Path("CONTEXT.md"),
    Path("ARCHITECTURE.md"), Path("docs/INDEX.md"), Path("docs/architecture/AGENTS.md"),
    Path("docs/architecture/DOCUMENT_ROUTING.md"), Path("docs/architecture/STATE_MACHINES.md"),
    Path("docs/architecture/DOMAIN_DECOUPLING.md"),
    Path("docs/integration/CROSS_REPO_INTEGRATION.md"),
    Path("docs/traceability/TRACEABILITY_INDEX.md"), Path(".agents/README.md"),
    Path(".agents/control-plane/README.md"),
)


def managed(content: str, begin: str = BEGIN, end: str = END) -> str:
    return f"{begin}\n{content.strip()}\n{end}"


def route_blocks(repository_id: str) -> dict[Path, str]:
    return {
        Path("README.md"): managed(f"""
## Modular Agent control plane

Repository: `{repository_id}`. This repository is a consumer of the portable `skills-shared` method plane.

```text
task → AGENTS router → selected architecture route → nearest README
→ immutable shared binding → consumer adapter → assertion → consumer receipt
```

Current-state authority remains in `CONTEXT.md`, machine bindings, exact forge subjects, and receipts. See `docs/INDEX.md`.
"""),
        Path("AGENTS.md"): managed("""
## Modular Agent bootstrap route

1. Read `README.md`, `CONTEXT.md`, `ARCHITECTURE.md`, and `docs/INDEX.md`.
2. Read the nearest governed-directory `README.md`.
3. Load `docs/architecture/DOMAIN_DECOUPLING.md` only for Skill, module, binding, adapter, provider-profile, or domain-boundary work.
4. Resolve `.agents/control-plane/source.json`, `.agents/control-plane/requirements.json`, and `.agents/bindings/repository-control-plane.json` before executing a shared procedure.
5. Treat scripts, verifiers, receipts, workflows, and exact Git/forge subjects as machine authority.

Do not copy a canonical shared `SKILL.md`. Do not infer runtime execution from a projection. Merge, release, permission expansion, and rollback remain Human/trusted-operator boundaries.
"""),
        Path("CLAUDE.md"): managed("""
Read `AGENTS.md` first. This file is a thin host projection and does not define a second procedure, binding, or evidence vocabulary.
"""),
        Path("CONTEXT.md"): managed("""
## Current modular handoff

The repository has a generated Domain Decoupling control-plane binding. Current issues, branches, providers, runtime state, and evidence belong here or in machine authorities; stable laws belong in `ARCHITECTURE.md` and `docs/architecture/DOMAIN_DECOUPLING.md`.
"""),
        Path("ARCHITECTURE.md"): managed("""
## Stable modular boundary

`skills-shared` owns portable procedures, ports, reusable controls, and schemas. This repository owns domain adapters, runtime choices, acceptance policy, current state, and execution receipts. Consumer specialization can only tighten constraints, narrow effects, increase evidence, or reduce authority.
"""),
        Path("docs/INDEX.md"): managed("""
## Standard modular routes

- `docs/architecture/AGENTS.md` — conditional architecture router.
- `docs/architecture/DOCUMENT_ROUTING.md` — route names and hop rules.
- `docs/architecture/STATE_MACHINES.md` — state/transition/evidence vocabulary.
- `docs/architecture/DOMAIN_DECOUPLING.md` — core/port/module/adapter laws.
- `docs/integration/CROSS_REPO_INTEGRATION.md` — repository ownership and binding flow.
- `docs/traceability/TRACEABILITY_INDEX.md` — source → decision → issue → PR → eval → receipt.
"""),
        Path("docs/architecture/AGENTS.md"): managed("""
## Conditional architecture router

Read only the matching topic:

- route or hop changes → `DOCUMENT_ROUTING.md`;
- state/transition changes → `STATE_MACHINES.md`;
- Skill/module/binding/adapter changes → `DOMAIN_DECOUPLING.md`;
- cross-repository ownership/release → `../integration/CROSS_REPO_INTEGRATION.md`;
- evidence lineage → `../traceability/TRACEABILITY_INDEX.md`.
"""),
        Path("docs/architecture/DOCUMENT_ROUTING.md"): managed("""
## Consumer route contract

```text
README/AGENTS → CONTEXT + ARCHITECTURE → docs/INDEX
→ selected topic route → nearest README → machine authority → exact evidence
```

`AGENTS.md` is a router, not a knowledge warehouse. Missing routes are `ABSENT`, not implicitly `NOT_APPLICABLE`.
"""),
        Path("docs/architecture/STATE_MACHINES.md"): managed("""
## Consumer bootstrap State Machine

```text
REPOSITORY_INSPECTED → ROUTES_BOUND → SHARED_SOURCE_BOUND
→ REQUIREMENTS_BOUND → CONSUMER_BINDING_GENERATED
→ RECEIPT_BOUND → VERIFIED
```

Failure terminals: `BLOCKED_MISSING_BINDING`, `BLOCKED_POLICY`, `FAIL`, `HUMAN_ADMIT_REQUIRED`. Documentation cannot create runtime `PASS`.
"""),
        Path("docs/architecture/DOMAIN_DECOUPLING.md"): managed("""
# Domain Decoupling Contract

Document ID: `DOMAIN-DECOUPLING-V1`  
Document Role: `CONSUMER_BINDING`  
Repository Plane: `INTEGRATION_ACCEPTANCE`

```text
portable shared core → immutable consumer binding → trigger-selected consumer adapter
→ consumer assertions → consumer-owned receipt
```

```text
ConsumerConstraints       ⊇ SharedCoreConstraints
ConsumerRequiredEvidence  ⊇ SharedRequiredEvidence
ConsumerAllowedEffects    ⊆ SharedAllowedEffects
ConsumerAuthority         ⊆ SharedMaximumAuthority
```

Domain-specific learning stays here. Generic reusable law is proposed upstream and adopted only through a new immutable binding.
"""),
        Path("docs/integration/CROSS_REPO_INTEGRATION.md"): managed("""
## Cross-repository binding flow

```text
skills-shared immutable subject
→ `.agents/control-plane/source.json`
→ consumer requirements
→ generated thin binding
→ consumer runtime/acceptance
→ consumer-owned receipt
```

A sibling checkout, symlink, mutable branch, package presence, or provider health is not a release identity.
"""),
        Path("docs/traceability/TRACEABILITY_INDEX.md"): managed("""
## Bootstrap traceability

```text
DOMAIN-DECOUPLING-V1
→ source pin
→ requirements/profile
→ generated binding
→ bootstrap receipt
→ owning exact-head workflow
```

The receipt records deterministic bootstrap only. Runtime, provider, merge, release, and rollback execution remain separate lanes.
"""),
        Path(".agents/README.md"): managed("""
## Generated control-plane routes

- `control-plane/source.json` — immutable shared source/interface/generator/adapter pin.
- `control-plane/profile.json` — selected portable profile.
- `control-plane/requirements.json` — requested shared Skill closure.
- `bindings/repository-control-plane.json` — generated content-bound Skill binding.
- `control-plane/bootstrap-receipt.json` — deterministic readback and rollback subject.

Project-local shared Skill bodies are forbidden; consumer adapters remain repository-owned.
"""),
        Path(".agents/control-plane/README.md"): managed("""
## Control-plane State Machine and authority

```text
SOURCE_PIN → PROFILE → REQUIREMENTS → GENERATED_BINDING → BOOTSTRAP_RECEIPT
```

JSON files in this directory are machine authorities. Do not edit generated files manually. Re-run the pinned bootstrap procedure and preserve the previous committed consumer subject for rollback.
"""),
    }


def split_block(text: str, path: Path, begin: str = BEGIN, end: str = END) -> tuple[str, str, str] | None:
    starts, ends = text.count(begin), text.count(end)
    if starts == ends == 0:
        return None
    if starts != 1 or ends != 1:
        raise BootstrapError(f"malformed or duplicate managed block: {path}")
    start = text.index(begin)
    finish = text.index(end, start) + len(end)
    return text[:start], text[start:finish], text[finish:]


def merge_block(current: str | None, block: str, path: Path, begin: str = BEGIN, end: str = END) -> str:
    if current is None:
        return block + "\n"
    parts = split_block(current, path, begin, end)
    if parts is None:
        separator = "" if current.endswith("\n\n") else ("\n" if current.endswith("\n") else "\n\n")
        return current + separator + block + "\n"
    return parts[0] + block + parts[2]


def observed_block(path: Path, begin: str = BEGIN, end: str = END) -> str:
    if not path.is_file() or path.is_symlink():
        raise BootstrapError(f"managed route missing or non-regular: {path}")
    parts = split_block(path.read_text(encoding="utf-8"), path, begin, end)
    if parts is None:
        raise BootstrapError(f"managed route block absent: {path}")
    return parts[1]


def workflow_text(shared_root: Path) -> str:
    text = (shared_root / WORKFLOW_ADAPTER).read_text(encoding="utf-8")
    if not text.startswith(WORKFLOW_MARKER + "\n"):
        raise BootstrapError("selected workflow adapter lacks its generated marker")
    return text
