#!/usr/bin/env python3
"""Scaffold and verify the thin, atomic dual-track-code-review-loop consumer profile.

Third sibling of `consumer_bootstrap.py` (default profile) and
`consumer_bootstrap_ghpc.py` (github-portfolio-control), built to the same
shape and for the same mechanical reason: `consumer_bootstrap.py --profile`
routes through `repository_control_plane.validate_profile`, which hard-fails on
`profile["skills"] != REQUIRED_ORDER` -- a hardcoded exact six-name, exact-order
list. Any profile selecting `dual-track-code-review-loop` is rejected there
before a byte is written, so a profile-namespaced sibling module is the only
live path. This module therefore never imports `repository_control_plane`; it
imports only the shared primitives (`consumer_bootstrap_common`,
`consumer_bootstrap_routes`, `consumer_bootstrap_receipt`).

Generated consumer surface -- exactly one managed block plus four authorities:

    AGENTS.md                                                          (managed block)
    .agents/control-plane/profiles/dual-track-code-review-loop.json
    .agents/control-plane/requirements/dual-track-code-review-loop.json
    .agents/bindings/dual-track-code-review-loop.json
    .agents/control-plane/bootstrap-receipt.dual-track-code-review-loop.json

The managed block ROUTES to the canonical prompt catalogue
(`skills/dual-track-code-review-loop/references/prompts/README.md`, pinned by
exact commit and blob) -- no prompt body, session-dispatch, handoff or receipt
body is copied into the consumer, and `.agents/prompt-packets/**`,
`.agents/session-dispatch/**`, `.agents/handoffs/**` and `.agents/receipts/**`
are deliberately out of scope: they have no generator, schema, fixture or
precedent anywhere in this repository, and a consumer's own receipts stay
consumer-owned.

Pin discipline: `subject_pin` is all-or-nothing per the profile schema, and this
profile declares NO unmerged candidate source, so `candidate_commit` MUST equal
`main_commit`. Mutable refs (`main`, `latest`, a branch name) are refused by the
`HEX40` fullmatch before anything is written.

What this module deliberately does NOT do: it never writes a `.github/workflows`
file, never claims a runtime, registry, hosted-workflow or provider lane, and
never promotes a green bootstrap into any of them. Because it targets no
workflow path at all, its workflow collision check is the contrapositive of the
default profile's: any consumer workflow carrying THIS profile's generated
marker is an impostor or a stale artifact of a substituted generator, and the
run fails closed on it.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import re
import subprocess
import sys
from typing import Any

from consumer_bootstrap_common import (
    BootstrapError, HEX40, REPOSITORY_ID, canonical, capture, ensure_git_worktree,
    json_text, preflight_generated, read_json, reject_copied_skill_bodies,
    reject_unsafe, repository_url, restore, run_git, git_out, sha256,
)
from consumer_bootstrap_receipt import validate_rollback
from consumer_bootstrap_routes import managed, merge_block, observed_block

SHARED_ROOT = Path(__file__).resolve().parents[3]

PROFILE_ID = "dual-track-code-review-loop"
PROFILE_SOURCE_DTCR = Path(
    "skills/shared-skills-infra/references/repository-control-plane-profile.dual-track-code-review-loop.json"
)
PROFILE_SCHEMA = "repository-control-plane-profile/v1"
BINDING_DOC_SCHEMA = "repository-control-plane-binding/v1"
REQUIREMENTS_SCHEMA = "shared-skills/consumer-requirements/v1"
BINDING_SCHEMA = "shared-skills/consumer-binding/v1"
DTCR_RECEIPT_SCHEMA = "shared-skills/consumer-bootstrap-receipt-dtcr/v1"

# A substring of neither existing pair, and containing neither:
# "DOMAIN DECOUPLING BOOTSTRAP" (default profile) and
# "GITHUB PORTFOLIO CONTROL BOOTSTRAP" (github-portfolio-control).
DTCR_MARKER_NAME = "DUAL TRACK CODE REVIEW BOOTSTRAP"
DTCR_BEGIN = f"<!-- BEGIN {DTCR_MARKER_NAME} -->"
DTCR_END = f"<!-- END {DTCR_MARKER_NAME} -->"
DTCR_WORKFLOW_MARKER = "# GENERATED BY DUAL-TRACK-CODE-REVIEW CONSUMER BOOTSTRAP"

MARKER_PAIR = re.compile(r"<!--\s*(?:BEGIN|END)\s+(?P<name>[A-Z0-9][A-Z0-9 _-]*?)\s*-->")

OWNED_TREE_PATH = "skills/dual-track-code-review-loop"
PROMPT_CATALOGUE = "skills/dual-track-code-review-loop/references/prompts/README.md"

DTCR_DOC_ROUTES = (Path("AGENTS.md"),)
DTCR_PROFILE_REL = Path(".agents/control-plane/profiles/dual-track-code-review-loop.json")
DTCR_REQUIREMENTS_REL = Path(".agents/control-plane/requirements/dual-track-code-review-loop.json")
DTCR_BINDING_REL = Path(".agents/bindings/dual-track-code-review-loop.json")
DTCR_RECEIPT_REL = Path(".agents/control-plane/bootstrap-receipt.dual-track-code-review-loop.json")

# Generated authorities owned by the other two profiles. This module must never
# write, and never even declare, any of them.
FOREIGN_AUTHORITIES = frozenset({
    Path(".agents/control-plane/source.json"),
    Path(".agents/control-plane/profile.json"),
    Path(".agents/control-plane/requirements.json"),
    Path(".agents/control-plane/bootstrap-receipt.json"),
    Path(".agents/bindings/repository-control-plane.json"),
    Path(".agents/control-plane/profiles/github-portfolio-control.json"),
    Path(".agents/control-plane/requirements/github-portfolio-control.json"),
    Path(".agents/control-plane/bootstrap-receipt.github-portfolio-control.json"),
    Path(".agents/bindings/github-portfolio-control.json"),
})

EXIT_COLLISION_MARKER = 65
EXIT_COLLISION_AUTHORITY = 66
EXIT_COLLISION_WORKFLOW = 67

DECLARED_BOUNDARIES = [
    "accept SDK/store/service terms",
    "change repository visibility",
    "choose private accounts",
    "claim business outcomes",
    "decide semantic conflicts",
    "execute physical hardware",
    "install credentials",
    "merge",
    "release",
]


class CollisionError(BootstrapError):
    """A pre-write governance/collision check failed with its own exit code."""

    def __init__(self, code: int, message: str) -> None:
        super().__init__(message)
        self.code = code


def generated_paths() -> set[Path]:
    return set(DTCR_DOC_ROUTES) | {
        DTCR_PROFILE_REL, DTCR_REQUIREMENTS_REL, DTCR_BINDING_REL, DTCR_RECEIPT_REL,
    }


def full_paths() -> list[Path]:
    return [DTCR_PROFILE_REL, DTCR_REQUIREMENTS_REL, DTCR_BINDING_REL]


def assert_generated_disjoint() -> None:
    """No generated path of this profile may be an authority owned by another."""
    overlap = sorted(p.as_posix() for p in generated_paths() & FOREIGN_AUTHORITIES)
    if overlap:
        raise BootstrapError(f"generated set claims a foreign profile's authority: {', '.join(overlap)}")


# ---------------------------------------------------------------------------
# profile document + subject-pin validation
# ---------------------------------------------------------------------------

REQUIRED_PIN_KEYS = {
    "main_commit", "owned_tree_path", "owned_tree",
    "candidate_commit", "candidate_source_path", "candidate_repin_policy",
}


def dtcr_profile_document(path: Path) -> dict[str, Any]:
    value = read_json(path)
    if value.get("schema") != PROFILE_SCHEMA:
        raise BootstrapError("unsupported control-plane profile")
    if value.get("profile") != PROFILE_ID:
        raise BootstrapError(f"profile is not the {PROFILE_ID} profile")
    skills = value.get("skills")
    if not isinstance(skills, list) or not skills or any(not isinstance(s, str) or not s for s in skills):
        raise BootstrapError("control-plane profile Skill closure is invalid")
    if PROFILE_ID not in skills:
        raise BootstrapError(f"control-plane profile does not select {PROFILE_ID}")
    authority = value.get("authority")
    if not isinstance(authority, dict) or not authority or any(v is not False for v in authority.values()):
        raise BootstrapError("control-plane profile widened automatic authority")
    validate_runtime_capabilities(value.get("runtime_capabilities"))
    pin = value.get("subject_pin")
    if not isinstance(pin, dict) or set(pin) != REQUIRED_PIN_KEYS:
        raise BootstrapError("control-plane profile is missing its subject pin")
    for key in ("main_commit", "owned_tree", "candidate_commit"):
        if not HEX40.fullmatch(str(pin[key])):
            raise BootstrapError(
                f"control-plane profile subject pin {key} is not an exact commit/tree SHA "
                "(a mutable ref such as main/latest is refused)"
            )
    if pin["candidate_commit"] != pin["main_commit"]:
        raise BootstrapError(
            "this profile declares no unmerged candidate source: candidate_commit must equal main_commit"
        )
    if pin["owned_tree_path"] != OWNED_TREE_PATH:
        raise BootstrapError(f"control-plane profile owned_tree_path must be {OWNED_TREE_PATH}")
    return value


def validate_runtime_capabilities(capabilities: Any) -> None:
    """`repository-control-plane-profile/v1` is `additionalProperties: false` and
    carries no field able to name an evidence path for a capability claim. A
    profile claiming an IMPLEMENTED installer or a PASSing service therefore
    makes an unprovable claim and is refused here rather than transcribed into a
    consumer authority. Broader language/build/provider capability claims have no
    field at all and stay NOT_IMPLEMENTED until a schema amendment is leased."""
    if not isinstance(capabilities, dict) or set(capabilities) != {"git_town", "forgejo"}:
        raise BootstrapError("control-plane profile runtime_capabilities drifted")
    git_town = capabilities["git_town"]
    forgejo = capabilities["forgejo"]
    if not isinstance(git_town, dict) or not isinstance(forgejo, dict):
        raise BootstrapError("control-plane profile runtime_capabilities entries are malformed")
    if git_town.get("installer_state") == "IMPLEMENTED":
        raise BootstrapError(
            "runtime_capabilities.git_town.installer_state=IMPLEMENTED has no evidence path in "
            "repository-control-plane-profile/v1; a supported-capability claim cannot be carried"
        )
    if forgejo.get("service_state") == "PASS":
        raise BootstrapError(
            "runtime_capabilities.forgejo.service_state=PASS has no evidence path in "
            "repository-control-plane-profile/v1; a supported-capability claim cannot be carried"
        )


def validate_subject_pin(shared_root: Path, pin: dict[str, str]) -> tuple[str, str]:
    """Prove the profile's declared subject pin is neither stale nor substituted,
    and return the running checkout's own (commit, tree)."""
    if git_out(shared_root, "status", "--porcelain", "--untracked-files=all"):
        raise BootstrapError("skills-shared source must be clean")
    head_commit = git_out(shared_root, "rev-parse", "HEAD")
    head_tree = git_out(shared_root, "rev-parse", "HEAD^{tree}")
    if not HEX40.fullmatch(head_commit) or not HEX40.fullmatch(head_tree):
        raise BootstrapError("invalid skills-shared commit/tree")

    main_commit = pin["main_commit"]
    probe = run_git(shared_root, "cat-file", "-t", main_commit, check=False)
    if probe.returncode or probe.stdout.strip() != "commit":
        raise BootstrapError("pinned main_commit is absent from this checkout's object database")
    if run_git(shared_root, "merge-base", "--is-ancestor", main_commit, head_commit, check=False).returncode:
        raise BootstrapError("pinned main_commit is not an ancestor of the running skills-shared checkout")

    observed_tree = git_out(shared_root, "rev-parse", f"{main_commit}:{pin['owned_tree_path']}")
    if observed_tree != pin["owned_tree"]:
        raise BootstrapError("pinned owned_tree does not match the pinned main_commit's tree")
    return head_commit, head_tree


def prompt_catalogue_pin(shared_root: Path, main_commit: str) -> dict[str, str]:
    """Pin the canonical prompt catalogue by exact blob -- the consumer receives
    this pointer, never these bytes."""
    relative = f"{main_commit}:{PROMPT_CATALOGUE}"
    result = subprocess.run(
        ["git", "-C", str(shared_root), "show", relative], capture_output=True, check=False
    )
    if result.returncode:
        raise BootstrapError(
            f"pinned prompt catalogue is absent: {relative}: "
            f"{result.stderr.decode('utf-8', 'replace').strip()}"
        )
    blob = git_out(shared_root, "rev-parse", relative)
    if not HEX40.fullmatch(blob):
        raise BootstrapError("invalid prompt catalogue blob identity")
    return {"path": PROMPT_CATALOGUE, "git_blob": blob, "sha256": sha256(result.stdout)}


# ---------------------------------------------------------------------------
# managed route block (exactly one)
# ---------------------------------------------------------------------------


def dtcr_route_blocks(repository_id: str, pin: dict[str, str], catalogue: dict[str, str]) -> dict[Path, str]:
    return {
        Path("AGENTS.md"): managed(
            "## Dual-track code review route\n\n"
            f"Repository: `{repository_id}`. This repository additionally carries the "
            "`dual-track-code-review-loop` profile: a thin, additive binding to the canonical "
            "dual-track procedure owned by `ed3c/skills-shared`.\n\n"
            "1. Resolve `.agents/control-plane/profiles/dual-track-code-review-loop.json`, "
            "`.agents/control-plane/requirements/dual-track-code-review-loop.json` and "
            "`.agents/bindings/dual-track-code-review-loop.json` before treating this repository "
            "as dual-track-bound.\n"
            "2. Read the Session prompts from the canonical catalogue at the pinned "
            f"skills-shared commit -- `{catalogue['path']}` "
            f"(commit `{pin['main_commit']}`, blob `{catalogue['git_blob']}`). This repository "
            "holds a route to those bodies, never a second copy of them.\n"
            "3. `.agents/control-plane/bootstrap-receipt.dual-track-code-review-loop.json` is the "
            "deterministic readback and rollback subject for this binding. It records scaffolding "
            "only: runtime, registry admission and hosted workflow are `NOT_EXERCISED`/`ABSENT`, "
            "never `PASS`.\n"
            "4. Do not copy a canonical `dual-track-code-review-loop` or `shared-skills-infra` "
            "Skill body, prompt body, module, schema or checker into this repository. This "
            "bootstrap generates no prompt packet, session dispatch, handoff or receipt body; "
            "this repository's own receipts stay repository-owned.\n"
            "5. Merge, release, promotion, permission expansion, semantic conflict adjudication "
            "and rollback stay Human/trusted-operator boundaries.",
            DTCR_BEGIN, DTCR_END,
        ),
    }


def apply_routes(consumer: Path, blocks: dict[Path, str]) -> None:
    for relative, block in blocks.items():
        path = consumer / relative
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(merge_block(current, block, relative, DTCR_BEGIN, DTCR_END), encoding="utf-8")


def check_routes(consumer: Path, blocks: dict[Path, str]) -> None:
    for relative, expected in blocks.items():
        observed = observed_block(consumer / relative, DTCR_BEGIN, DTCR_END)
        if observed != expected:
            raise BootstrapError(f"managed route block drifted: {relative}")


def write_full(consumer: Path, relative: Path, text: str) -> None:
    path = consumer / relative
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def check_full(consumer: Path, relative: Path, expected_text: str) -> None:
    path = consumer / relative
    if not path.is_file() or path.is_symlink():
        raise BootstrapError(f"generated artifact missing or non-regular: {relative}")
    if path.read_text(encoding="utf-8") != expected_text:
        raise BootstrapError(f"generated artifact drifted: {relative}")


# ---------------------------------------------------------------------------
# content-addressed skill digests (matches shared_skills.content_digest)
# ---------------------------------------------------------------------------


def content_sha256(path: Path) -> str:
    if not path.is_dir():
        raise BootstrapError(f"cannot digest missing Skill directory: {path}")
    sha = hashlib.sha256()
    for file in sorted(p for p in path.rglob("*") if p.is_file() and "__pycache__" not in p.parts):
        sha.update(file.relative_to(path).as_posix().encode("utf-8"))
        sha.update(b"\0")
        sha.update(file.read_bytes())
        sha.update(b"\0")
    return sha.hexdigest()


# ---------------------------------------------------------------------------
# generated JSON authorities
# ---------------------------------------------------------------------------


def build_profile_binding(profile_doc: dict[str, Any]) -> dict[str, Any]:
    return {
        "schema": BINDING_DOC_SCHEMA,
        "profile": profile_doc["profile"],
        "profile_sha256": sha256(canonical(profile_doc)),
        "skills": list(profile_doc["skills"]),
        "runtime_capabilities": profile_doc["runtime_capabilities"],
        "authority": profile_doc["authority"],
        "subject_pin": profile_doc["subject_pin"],
    }


def build_requirements(skills: list[str]) -> dict[str, Any]:
    return {
        "schema": REQUIREMENTS_SCHEMA,
        "binding": PROFILE_ID,
        "shared": sorted(skills),
        "repo_owned": [],
        "surfaces": {"claude": ".claude/skills", "codex": ".agents/skills"},
        "egress": {"policy": "DENY_BY_DEFAULT", "allowed_hosts": []},
    }


def build_binding(
    repository_url_value: str, shared_commit: str, shared_tree: str, pin: dict[str, str],
    skills: list[str], shared_root: Path, requirements: dict[str, Any],
    catalogue: dict[str, str],
) -> dict[str, Any]:
    rows = [
        {
            "name": name, "content_sha256": content_sha256(shared_root / "skills" / name),
            "entrypoint": f"skills/{name}/SKILL.md",
        }
        for name in sorted(skills)
    ]
    binding = {
        "schema": BINDING_SCHEMA,
        "binding": PROFILE_ID,
        "source": {"repository": repository_url_value, "commit": shared_commit, "tree": shared_tree},
        "pinned_subject": pin,
        "prompt_catalogue": catalogue,
        "requirements_sha256": sha256(json_text(requirements).encode("utf-8")),
        "skills": rows,
        "repo_owned": [],
        "surfaces": requirements["surfaces"],
    }
    binding["content_sha256"] = sha256(canonical(binding))
    return binding


# ---------------------------------------------------------------------------
# canonical-body-copy refusal
# ---------------------------------------------------------------------------


def assert_no_canonical_body_copied(shared_root: Path, skills: list[str], texts: dict[str, str]) -> None:
    bodies: dict[str, str] = {}
    for name in skills:
        path = shared_root / "skills" / name / "SKILL.md"
        if path.is_file():
            bodies[f"skills/{name}/SKILL.md"] = path.read_text(encoding="utf-8")
    for relative in (
        f"{OWNED_TREE_PATH}/AGENTS.md", f"{OWNED_TREE_PATH}/README.md", PROMPT_CATALOGUE,
    ):
        path = shared_root / relative
        if path.is_file():
            bodies[relative] = path.read_text(encoding="utf-8")
    for generated_path, text in texts.items():
        for body_path, body_text in bodies.items():
            if body_text and body_text in text:
                raise BootstrapError(
                    f"generated {generated_path} embeds canonical body bytes copied from {body_path}"
                )


# ---------------------------------------------------------------------------
# receipt
# ---------------------------------------------------------------------------


def expected_evidence() -> dict[str, str]:
    return {
        "route_scaffold": "PASS",
        "immutable_source_binding": "PASS",
        "prompt_catalogue_routing": "PASS",
        "byte_readback": "PASS",
        "runtime": "NOT_EXERCISED",
        "registry_admission": "ABSENT",
        "hosted_workflow": "NOT_EXERCISED",
        "real_consumer": "NOT_SELECTED",
        "consumer_canary": "NOT_EXERCISED",
        "composition_target_430": "ABSENT",
        "language_build_provider_capability": "NOT_IMPLEMENTED",
        "completion_dependency_525": "OPEN",
        "host_skill_discovery": "NOT_EXERCISED",
        "agent_runtime_execution": "NOT_EXERCISED",
        "provider_execution": "NOT_EXERCISED",
        "merge": "HUMAN_ADMIT_REQUIRED",
        "release": "HUMAN_ADMIT_REQUIRED",
        "rollback_execution": "NOT_EXERCISED",
        "terminal": "NOT_EMITTED",
    }


def artifact_records(consumer: Path, blocks: dict[Path, str], fulls: list[Path]) -> list[dict[str, str]]:
    records: list[dict[str, str]] = []
    for relative in blocks:
        observed = observed_block(consumer / relative, DTCR_BEGIN, DTCR_END)
        records.append({
            "path": relative.as_posix(), "managed_block_sha256": sha256(observed.encode("utf-8")),
            "state": "MANAGED_BLOCK",
        })
    for relative in fulls:
        path = consumer / relative
        if not path.is_file() or path.is_symlink():
            raise BootstrapError(f"generated artifact missing or non-regular: {relative}")
        records.append({"path": relative.as_posix(), "sha256": sha256(path.read_bytes()), "state": "GENERATED"})
    return sorted(records, key=lambda row: row["path"])


def build_dtcr_receipt(
    repository_id: str, repository_url_value: str, shared_commit: str, shared_tree: str,
    pin: dict[str, str], catalogue: dict[str, str], rollback: dict[str, str],
    artifacts: list[dict[str, str]], binding: dict[str, Any], profile_doc: dict[str, Any],
) -> dict[str, Any]:
    subject = {
        "consumer_repository": repository_id, "rollback": rollback,
        "shared_commit": shared_commit, "shared_tree": shared_tree, "artifacts": artifacts,
    }
    receipt: dict[str, Any] = {
        "schema": DTCR_RECEIPT_SCHEMA,
        "consumer": {
            "repository": repository_id, "generated_subject_sha256": sha256(canonical(subject)),
        },
        "shared_subject": {
            "repository": repository_url_value, "commit": shared_commit, "tree": shared_tree,
            "pinned_main_commit": pin["main_commit"],
            "pinned_owned_tree_path": pin["owned_tree_path"],
            "pinned_owned_tree": pin["owned_tree"],
            "pinned_candidate_commit": pin["candidate_commit"],
            "pinned_candidate_source_path": pin["candidate_source_path"],
            "prompt_catalogue": catalogue,
        },
        "profile": {
            "id": profile_doc["profile"], "sha256": sha256(canonical(profile_doc)),
            "skills": list(profile_doc["skills"]),
        },
        "binding": {
            "path": DTCR_BINDING_REL.as_posix(), "semantic_sha256": sha256(canonical(binding)),
            "content_sha256": binding["content_sha256"],
        },
        "artifacts": artifacts,
        "evidence": expected_evidence(),
        "authority": {
            "automatic_merge": False, "automatic_conflict_resolution": False,
            "visibility_change": False, "credential_values": False,
            "provider_activation": False, "production_writeback": False,
        },
        "declared_boundaries": list(DECLARED_BOUNDARIES),
        "rollback": rollback,
        "decision_record_policy": "OBSERVATIONS_AND_DECISIONS_ONLY",
    }
    receipt["receipt_sha256"] = sha256(canonical(receipt))
    return receipt


def validate_dtcr_receipt_shape(receipt: dict[str, Any]) -> None:
    required = {
        "schema", "consumer", "shared_subject", "profile", "binding", "artifacts",
        "evidence", "authority", "declared_boundaries", "rollback",
        "decision_record_policy", "receipt_sha256",
    }
    if set(receipt) != required or receipt.get("schema") != DTCR_RECEIPT_SCHEMA:
        raise BootstrapError("dtcr bootstrap receipt schema or fields drifted")
    reject_unsafe(receipt)
    unsigned = dict(receipt)
    claimed = unsigned.pop("receipt_sha256", None)
    if claimed != sha256(canonical(unsigned)):
        raise BootstrapError("dtcr bootstrap receipt self digest is stale")
    if receipt.get("decision_record_policy") != "OBSERVATIONS_AND_DECISIONS_ONLY":
        raise BootstrapError("dtcr bootstrap receipt attempted to persist private reasoning")
    authority = receipt.get("authority")
    if not isinstance(authority, dict) or not authority or any(v is not False for v in authority.values()):
        raise BootstrapError("dtcr bootstrap receipt widened automatic authority")
    if receipt.get("declared_boundaries") != DECLARED_BOUNDARIES:
        raise BootstrapError("dtcr bootstrap receipt declared-boundary list drifted")
    if receipt.get("evidence") != expected_evidence():
        raise BootstrapError("dtcr bootstrap receipt promoted an unexercised or Human-owned lane")
    rollback = receipt.get("rollback")
    if not isinstance(rollback, dict) or set(rollback) != {"commit", "tree"}:
        raise BootstrapError("dtcr bootstrap receipt rollback subject is absent")
    if not HEX40.fullmatch(rollback["commit"]) or not HEX40.fullmatch(rollback["tree"]):
        raise BootstrapError("dtcr bootstrap receipt rollback identity is mutable")


def validate_dtcr_receipt(consumer: Path, expected: dict[str, Any]) -> None:
    path = consumer / DTCR_RECEIPT_REL
    if not path.is_file() or path.is_symlink():
        raise BootstrapError("dtcr bootstrap receipt missing or non-regular")
    observed = read_json(path)
    validate_dtcr_receipt_shape(observed)
    validate_rollback(consumer, observed["rollback"])
    if observed != expected:
        raise BootstrapError("dtcr bootstrap receipt is stale or substituted")
    for row in observed["artifacts"]:
        relative = row["path"]
        artifact = consumer / relative
        if not artifact.is_file() or artifact.is_symlink():
            raise BootstrapError(f"dtcr bootstrap receipt artifact is stale: {relative}")
        if row["state"] == "MANAGED_BLOCK":
            observed_digest = sha256(observed_block(artifact, DTCR_BEGIN, DTCR_END).encode("utf-8"))
        else:
            observed_digest = sha256(artifact.read_bytes())
        expected_digest = row.get("managed_block_sha256") or row.get("sha256")
        if observed_digest != expected_digest:
            raise BootstrapError(f"dtcr bootstrap receipt artifact is stale: {relative}")


def rollback_subject(consumer: Path, initial_commit: str, initial_tree: str) -> dict[str, str]:
    receipt_path = consumer / DTCR_RECEIPT_REL
    if not receipt_path.is_file():
        return {"commit": initial_commit, "tree": initial_tree}
    receipt = read_json(receipt_path)
    validate_dtcr_receipt_shape(receipt)
    validate_rollback(consumer, receipt["rollback"])
    return receipt["rollback"]


# ---------------------------------------------------------------------------
# EXISTING_GOVERNANCE_DISCOVERED -> COMPATIBILITY_AND_COLLISION_CHECKED
# ---------------------------------------------------------------------------


def preflight_collisions(consumer: Path) -> None:
    """Enumerate the consumer's managed marker pairs, generated JSON authorities
    and workflow files BEFORE any write. Each case has its own exit code."""
    for relative in DTCR_DOC_ROUTES:
        path = consumer / relative
        if not path.is_file() or path.is_symlink():
            continue
        for name in sorted({m.group("name") for m in MARKER_PAIR.finditer(path.read_text(encoding="utf-8"))}):
            if name == DTCR_MARKER_NAME:
                continue
            if name in DTCR_MARKER_NAME or DTCR_MARKER_NAME in name:
                raise CollisionError(
                    EXIT_COLLISION_MARKER,
                    f"existing managed marker pair collides with this profile's pair in {relative}: "
                    f"<!-- BEGIN {name} -->",
                )

    for relative, schemas in (
        (DTCR_PROFILE_REL, {BINDING_DOC_SCHEMA}),
        (DTCR_REQUIREMENTS_REL, {REQUIREMENTS_SCHEMA}),
        (DTCR_BINDING_REL, {BINDING_SCHEMA}),
        (DTCR_RECEIPT_REL, {DTCR_RECEIPT_SCHEMA}),
    ):
        try:
            preflight_generated(consumer / relative, schemas)
        except BootstrapError as exc:
            raise CollisionError(EXIT_COLLISION_AUTHORITY, str(exc)) from exc

    workflows = consumer / ".github/workflows"
    if workflows.is_dir():
        for path in sorted(workflows.iterdir()):
            if not path.is_file() or path.is_symlink():
                continue
            if DTCR_WORKFLOW_MARKER in path.read_text(encoding="utf-8", errors="replace"):
                raise CollisionError(
                    EXIT_COLLISION_WORKFLOW,
                    f"workflow claims this profile's generated marker but this profile generates no "
                    f"workflow: {path.relative_to(consumer).as_posix()}",
                )


def assert_single_owner(consumer: Path) -> None:
    """Refuse a second task-state owner under this profile id."""
    path = consumer / DTCR_BINDING_REL
    if not path.is_file() or path.is_symlink():
        return
    observed = read_json(path).get("binding")
    if observed != PROFILE_ID:
        raise BootstrapError(
            f"duplicate task-state owner: {DTCR_BINDING_REL.as_posix()} is owned by {observed!r}, "
            f"not {PROFILE_ID!r}"
        )


# ---------------------------------------------------------------------------
# orchestration
# ---------------------------------------------------------------------------


def bootstrap_consumer_dtcr(
    *, consumer: Path, repository_id: str, profile_path: Path, apply: bool,
    shared_root: Path = SHARED_ROOT,
) -> None:
    if not REPOSITORY_ID.fullmatch(repository_id):
        raise BootstrapError("repository-id must be owner/name")
    consumer = consumer.resolve()
    initial_commit, initial_tree = ensure_git_worktree(consumer)

    assert_generated_disjoint()
    profile_doc = dtcr_profile_document(profile_path)
    pin = profile_doc["subject_pin"]
    skills = list(profile_doc["skills"])
    shared_commit, shared_tree = validate_subject_pin(shared_root, pin)
    catalogue = prompt_catalogue_pin(shared_root, pin["main_commit"])
    repository_url_value = repository_url(shared_root)

    blocks = dtcr_route_blocks(repository_id, pin, catalogue)
    requirements = build_requirements(skills)
    profile_binding = build_profile_binding(profile_doc)
    fulls = full_paths()

    preflight_collisions(consumer)
    assert_single_owner(consumer)
    reject_copied_skill_bodies(consumer, skills)

    if apply:
        rollback = rollback_subject(consumer, initial_commit, initial_tree)
        snapshot = capture(consumer, generated_paths())
        try:
            apply_routes(consumer, blocks)
            write_full(consumer, DTCR_PROFILE_REL, json_text(profile_binding))
            write_full(consumer, DTCR_REQUIREMENTS_REL, json_text(requirements))
            binding = build_binding(
                repository_url_value, shared_commit, shared_tree, pin, skills, shared_root,
                requirements, catalogue,
            )
            write_full(consumer, DTCR_BINDING_REL, json_text(binding))

            generated_texts = {
                p.as_posix(): (consumer / p).read_text(encoding="utf-8") for p in (*blocks, *fulls)
            }
            assert_no_canonical_body_copied(shared_root, skills, generated_texts)

            artifacts = artifact_records(consumer, blocks, fulls)
            receipt = build_dtcr_receipt(
                repository_id, repository_url_value, shared_commit, shared_tree, pin, catalogue,
                rollback, artifacts, binding, profile_doc,
            )
            write_full(consumer, DTCR_RECEIPT_REL, json_text(receipt))
            validate_dtcr_receipt(consumer, receipt)
        except Exception:
            restore(consumer, snapshot)
            raise
    else:
        check_routes(consumer, blocks)
        check_full(consumer, DTCR_PROFILE_REL, json_text(profile_binding))
        check_full(consumer, DTCR_REQUIREMENTS_REL, json_text(requirements))
        binding = build_binding(
            repository_url_value, shared_commit, shared_tree, pin, skills, shared_root,
            requirements, catalogue,
        )
        check_full(consumer, DTCR_BINDING_REL, json_text(binding))

        generated_texts = {
            p.as_posix(): (consumer / p).read_text(encoding="utf-8") for p in (*blocks, *fulls)
        }
        assert_no_canonical_body_copied(shared_root, skills, generated_texts)

        existing = read_json(consumer / DTCR_RECEIPT_REL)
        validate_dtcr_receipt_shape(existing)
        validate_rollback(consumer, existing["rollback"])
        artifacts = artifact_records(consumer, blocks, fulls)
        expected = build_dtcr_receipt(
            repository_id, repository_url_value, shared_commit, shared_tree, pin, catalogue,
            existing["rollback"], artifacts, binding, profile_doc,
        )
        validate_dtcr_receipt(consumer, expected)

    print(
        "DTCR-BOOTSTRAP-GREEN "
        f"consumer={repository_id} shared={shared_commit[:12]} routes={len(blocks)} "
        f"mode={'apply' if apply else 'check'} runtime=NOT_EXERCISED registry_admission=ABSENT "
        "hosted_workflow=NOT_EXERCISED real_consumer=NOT_SELECTED completion_dependency_525=OPEN "
        "merge=HUMAN_ADMIT_REQUIRED terminal=NOT_EMITTED"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--consumer", required=True, type=Path)
    parser.add_argument("--repository-id", required=True)
    parser.add_argument("--profile", type=Path, default=PROFILE_SOURCE_DTCR)
    parser.add_argument("--shared-root", type=Path, default=SHARED_ROOT)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--apply", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    shared_root = args.shared_root.resolve()
    profile = args.profile if args.profile.is_absolute() else shared_root / args.profile
    try:
        bootstrap_consumer_dtcr(
            consumer=args.consumer, repository_id=args.repository_id,
            profile_path=profile, apply=args.apply, shared_root=shared_root,
        )
        return 0
    except CollisionError as exc:
        print(f"DTCR-BOOTSTRAP-COLLISION {exc}", file=sys.stderr)
        return exc.code
    except BootstrapError as exc:
        print(f"DTCR-BOOTSTRAP-RED {exc}", file=sys.stderr)
        return 2
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        print(f"DTCR-BOOTSTRAP-INVALID {exc}", file=sys.stderr)
        return 64


if __name__ == "__main__":
    raise SystemExit(main())
