#!/usr/bin/env python3
"""Scaffold and verify the thin, atomic github-portfolio-control consumer profile.

Sibling to `consumer_bootstrap.py`, not a replacement for it: the default
profile keeps its own single fixed set of generated paths
(`.agents/control-plane/{source,profile,requirements}.json`,
`.agents/bindings/repository-control-plane.json`, ...) untouched. This module
adds a second, profile-namespaced bootstrap so a consumer can carry the
`github-portfolio-control` profile alongside (or instead of) the default one,
without either overwriting the other's generated paths.

Everything that is not specific to the github-portfolio-control profile is
imported from `consumer_bootstrap_common.py` (git/JSON/atomicity primitives)
and `consumer_bootstrap_routes.py` (managed-block merge/observe, parameterized
by this module's own begin/end markers so the default profile's blocks and
this profile's blocks can coexist in the same README.md/AGENTS.md without
collision) and `consumer_bootstrap_receipt.py` (rollback ancestry check).

Pin discipline: the profile pins three skills-shared subjects --
{main_commit, the exact tree of skills/github-portfolio-control at that
commit, and a not-yet-merged portfolio-core candidate commit the seven
Codex agent prompt templates are sourced from}. `validate_subject_pin`
refuses a substituted or non-ancestor pin before anything is written.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import subprocess
import sys
from typing import Any

from consumer_bootstrap_common import (
    BootstrapError, HEX40, REPOSITORY_ID, canonical, capture, ensure_git_worktree,
    json_text, preflight_generated, read_json, reject_copied_skill_bodies,
    reject_unsafe, repository_url, restore, run_git, git_out, sha256,
)
from consumer_bootstrap_receipt import validate_rollback
from consumer_bootstrap_routes import managed, merge_block, observed_block

SHARED_ROOT = Path(__file__).resolve().parents[3]

PROFILE_ID = "github-portfolio-control"
PROFILE_SOURCE_GHPC = Path(
    "skills/shared-skills-infra/references/repository-control-plane-profile.github-portfolio-control.json"
)
PROFILE_SCHEMA = "repository-control-plane-profile/v1"
BINDING_DOC_SCHEMA = "repository-control-plane-binding/v1"
REQUIREMENTS_SCHEMA = "shared-skills/consumer-requirements/v1"
BINDING_SCHEMA = "shared-skills/consumer-binding/v1"
GHPC_RECEIPT_SCHEMA = "shared-skills/consumer-bootstrap-receipt-ghpc/v1"
STUB_SCHEMA = "portfolio-stub/v1"

GHPC_BEGIN = "<!-- BEGIN GITHUB PORTFOLIO CONTROL BOOTSTRAP -->"
GHPC_END = "<!-- END GITHUB PORTFOLIO CONTROL BOOTSTRAP -->"
CODEX_MARKER = "# GENERATED BY GITHUB-PORTFOLIO-CONTROL CONSUMER BOOTSTRAP"

GHPC_DOC_ROUTES = (
    Path("README.md"), Path("AGENTS.md"), Path("docs/traceability/github-portfolio-control.md"),
)
GHPC_PROFILE_REL = Path(".agents/control-plane/profiles/github-portfolio-control.json")
GHPC_REQUIREMENTS_REL = Path(".agents/control-plane/requirements/github-portfolio-control.json")
GHPC_BINDING_REL = Path(".agents/bindings/github-portfolio-control.json")
GHPC_RECEIPT_REL = Path(".agents/control-plane/bootstrap-receipt.github-portfolio-control.json")
CODEX_CONFIG_REL = Path(".codex/config.toml")

PORTFOLIO_STUB_RELS = {
    "snapshot": Path(".agents/portfolio/snapshot.json"),
    "acceptance-ledger": Path(".agents/portfolio/acceptance-ledger.json"),
    "multigraph": Path(".agents/portfolio/multigraph.json"),
    "local-handoff-queue": Path(".agents/portfolio/local-handoff-queue.json"),
}

# The seven subagent roles github-portfolio-control's own
# references/controlled-vocabulary.md names. Fixed and ordered: a template
# renamed or dropped upstream must be a deliberate edit here, not silently
# picked up or silently missing.
CODEX_ROLES = (
    "portfolio-explorer", "acceptance-adversary", "dependency-auditor",
    "runtime-admission-auditor", "implementation-worker",
    "consolidation-verifier", "release-auditor",
)


def codex_agent_rel(role: str) -> Path:
    return Path(f".codex/agents/{role}.toml")


def generated_paths() -> set[Path]:
    paths = set(GHPC_DOC_ROUTES) | {
        GHPC_PROFILE_REL, GHPC_REQUIREMENTS_REL, GHPC_BINDING_REL, GHPC_RECEIPT_REL, CODEX_CONFIG_REL,
    }
    paths |= set(PORTFOLIO_STUB_RELS.values())
    paths |= {codex_agent_rel(role) for role in CODEX_ROLES}
    return paths


# ---------------------------------------------------------------------------
# profile document + subject-pin validation
# ---------------------------------------------------------------------------

REQUIRED_PIN_KEYS = {
    "main_commit", "owned_tree_path", "owned_tree",
    "candidate_commit", "candidate_source_path", "candidate_repin_policy",
}


def ghpc_profile_document(path: Path) -> dict[str, Any]:
    value = read_json(path)
    if value.get("schema") != PROFILE_SCHEMA:
        raise BootstrapError("unsupported control-plane profile")
    if value.get("profile") != PROFILE_ID:
        raise BootstrapError(f"profile is not the {PROFILE_ID} profile")
    skills = value.get("skills")
    if not isinstance(skills, list) or not skills or any(not isinstance(s, str) or not s for s in skills):
        raise BootstrapError("control-plane profile Skill closure is invalid")
    authority = value.get("authority")
    if not isinstance(authority, dict) or not authority or any(v is not False for v in authority.values()):
        raise BootstrapError("control-plane profile widened automatic authority")
    pin = value.get("subject_pin")
    if not isinstance(pin, dict) or set(pin) != REQUIRED_PIN_KEYS:
        raise BootstrapError("control-plane profile is missing its subject pin")
    for key in ("main_commit", "owned_tree", "candidate_commit"):
        if not HEX40.fullmatch(pin[key]):
            raise BootstrapError(f"control-plane profile subject pin {key} is not an exact commit/tree SHA")
    return value


def validate_subject_pin(shared_root: Path, pin: dict[str, str]) -> tuple[str, str]:
    """Prove the profile's declared subject pin is neither stale nor
    substituted, and return the running checkout's own (commit, tree)."""
    if git_out(shared_root, "status", "--porcelain", "--untracked-files=all"):
        raise BootstrapError("skills-shared source must be clean")
    head_commit = git_out(shared_root, "rev-parse", "HEAD")
    head_tree = git_out(shared_root, "rev-parse", "HEAD^{tree}")
    if not HEX40.fullmatch(head_commit) or not HEX40.fullmatch(head_tree):
        raise BootstrapError("invalid skills-shared commit/tree")

    main_commit = pin["main_commit"]
    if run_git(shared_root, "cat-file", "-e", main_commit, check=False).returncode:
        raise BootstrapError("pinned main_commit is absent from this checkout's object database")
    if run_git(shared_root, "merge-base", "--is-ancestor", main_commit, head_commit, check=False).returncode:
        raise BootstrapError("pinned main_commit is not an ancestor of the running skills-shared checkout")

    observed_tree = git_out(shared_root, "rev-parse", f"{main_commit}:{pin['owned_tree_path']}")
    if observed_tree != pin["owned_tree"]:
        raise BootstrapError("pinned owned_tree does not match the pinned main_commit's tree")

    candidate = pin["candidate_commit"]
    probe = run_git(shared_root, "cat-file", "-t", candidate, check=False)
    if probe.returncode or probe.stdout.strip() != "commit":
        raise BootstrapError("pinned candidate_commit is absent or not a commit")
    if run_git(shared_root, "merge-base", "--is-ancestor", main_commit, candidate, check=False).returncode:
        raise BootstrapError("pinned candidate_commit does not descend from the pinned main_commit")

    return head_commit, head_tree


# ---------------------------------------------------------------------------
# managed doc routes
# ---------------------------------------------------------------------------


def ghpc_route_blocks(repository_id: str) -> dict[Path, str]:
    return {
        Path("README.md"): managed(
            "## GitHub portfolio control\n\n"
            f"Repository: `{repository_id}`. This repository additionally carries the "
            "`github-portfolio-control` profile: a thin, additive binding to the portfolio "
            "join contracts owned by `github-portfolio-control` and composed by "
            "`agentic-tech-lead-orchestration`, `procedural-shadow-runtime`, "
            "`github-delivery-loop` and `git-town-stacked-pr-worker`.\n\n"
            "```text\n"
            "repository-control-plane binding (see above)\n"
            "-> portfolio profile/requirements/binding under .agents/control-plane/profiles,requirements/\n"
            "-> .agents/bindings/github-portfolio-control.json\n"
            "-> empty portfolio stubs under .agents/portfolio/\n"
            "-> thin Codex agent bindings under .codex/\n"
            "```\n\n"
            "No portfolio snapshot, acceptance, multigraph or dispatch decision exists yet; the "
            "four `.agents/portfolio/*.json` files are bootstrap stubs, not observed state. See "
            "`docs/traceability/github-portfolio-control.md`.",
            GHPC_BEGIN, GHPC_END,
        ),
        Path("AGENTS.md"): managed(
            "## GitHub portfolio control route\n\n"
            "1. Resolve `.agents/control-plane/profiles/github-portfolio-control.json`, "
            "`.agents/control-plane/requirements/github-portfolio-control.json` and "
            "`.agents/bindings/github-portfolio-control.json` before treating this repository "
            "as portfolio-control-bound.\n"
            "2. Treat the four `.agents/portfolio/*.json` files (snapshot, acceptance-ledger, "
            "multigraph, local-handoff-queue) as empty bootstrap stubs, never as an observed "
            "epoch, until a real portfolio run overwrites them.\n"
            "3. Treat `.codex/config.toml` and `.codex/agents/*.toml` as thin, unresolved "
            "(`ALIAS_ONLY`) bindings. Do not infer an exact provider, model or exercised "
            "identity from their presence.\n"
            "4. Do not copy a canonical `github-portfolio-control`, "
            "`agentic-tech-lead-orchestration`, `procedural-shadow-runtime`, "
            "`github-delivery-loop` or `git-town-stacked-pr-worker` Skill body into this "
            "repository. Merge, release, promotion, permission expansion and rollback stay "
            "Human/trusted-operator boundaries.",
            GHPC_BEGIN, GHPC_END,
        ),
        Path("docs/traceability/github-portfolio-control.md"): managed(
            "# github-portfolio-control bootstrap traceability\n\n"
            f"Repository: `{repository_id}`.\n\n"
            "```text\n"
            "skills-shared subject_pin (main, owned_tree, candidate)\n"
            "-> .agents/control-plane/profiles/github-portfolio-control.json\n"
            "-> .agents/control-plane/requirements/github-portfolio-control.json\n"
            "-> .agents/bindings/github-portfolio-control.json\n"
            "-> .agents/portfolio/*.json (empty stubs: snapshot, acceptance-ledger, "
            "multigraph, local-handoff-queue)\n"
            "-> .codex/config.toml, .codex/agents/*.toml (thin, ALIAS_ONLY)\n"
            "-> bootstrap receipt (hosted_evidence=NOT_EXERCISED)\n"
            "```\n\n"
            "This document records deterministic bootstrap scaffolding only. It does not "
            "establish that any subagent ran, that any alias resolved to an exercised model, "
            "or that any hosted workflow executed. Human Admit owns merge, release, promotion "
            "and production.",
            GHPC_BEGIN, GHPC_END,
        ),
    }


def apply_routes(consumer: Path, blocks: dict[Path, str]) -> None:
    for relative, block in blocks.items():
        path = consumer / relative
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(merge_block(current, block, relative, GHPC_BEGIN, GHPC_END), encoding="utf-8")


def check_routes(consumer: Path, blocks: dict[Path, str]) -> None:
    for relative, expected in blocks.items():
        observed = observed_block(consumer / relative, GHPC_BEGIN, GHPC_END)
        if observed != expected:
            raise BootstrapError(f"managed route block drifted: {relative}")


def write_full(consumer: Path, relative: Path, text: str) -> None:
    path = consumer / relative
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def check_full(consumer: Path, relative: Path, expected_text: str) -> None:
    path = consumer / relative
    if not path.is_file() or path.is_symlink():
        raise BootstrapError(f"generated artifact missing or non-regular: {relative}")
    if path.read_text(encoding="utf-8") != expected_text:
        raise BootstrapError(f"generated artifact drifted: {relative}")


# ---------------------------------------------------------------------------
# content-addressed skill digests (matches shared_skills.content_digest)
# ---------------------------------------------------------------------------


def content_sha256(path: Path) -> str:
    if not path.is_dir():
        raise BootstrapError(f"cannot digest missing Skill directory: {path}")
    sha = hashlib.sha256()
    for file in sorted(p for p in path.rglob("*") if p.is_file() and "__pycache__" not in p.parts):
        sha.update(file.relative_to(path).as_posix().encode("utf-8"))
        sha.update(b"\0")
        sha.update(file.read_bytes())
        sha.update(b"\0")
    return sha.hexdigest()


# ---------------------------------------------------------------------------
# pinned Codex agent templates
# ---------------------------------------------------------------------------


def read_candidate_blob(shared_root: Path, candidate: str, relative: str) -> tuple[str, str]:
    result = subprocess.run(
        ["git", "-C", str(shared_root), "show", f"{candidate}:{relative}"],
        capture_output=True, check=False,
    )
    if result.returncode:
        raise BootstrapError(
            f"cannot read pinned candidate blob {candidate}:{relative}: "
            f"{result.stderr.decode('utf-8', 'replace').strip()}"
        )
    blob = git_out(shared_root, "rev-parse", f"{candidate}:{relative}")
    if not HEX40.fullmatch(blob):
        raise BootstrapError(f"invalid candidate blob identity for {relative}")
    return result.stdout.decode("utf-8"), blob


def codex_agent_texts(shared_root: Path, pin: dict[str, str]) -> dict[str, tuple[str, str, str]]:
    """role -> (generated .toml text, source template relative path, source git blob sha)."""
    result: dict[str, tuple[str, str, str]] = {}
    for role in CODEX_ROLES:
        relative = f"{pin['candidate_source_path']}/{role}.toml.template"
        body, blob = read_candidate_blob(shared_root, pin["candidate_commit"], relative)
        text = (
            f"{CODEX_MARKER}\n"
            f"# source: {pin['candidate_commit']}:{relative} (git_blob={blob})\n"
            "# ${MODEL_ID} and ${REASONING_EFFORT} are unresolved ALIAS_ONLY placeholders;\n"
            "# Human Admit must resolve them before this agent may be dispatched.\n\n"
            f"{body}"
        )
        result[role] = (text, relative, blob)
    return result


def codex_config_text(pin: dict[str, str]) -> str:
    lines = [
        CODEX_MARKER,
        "# thin binding only -- no canonical prompt body is authored here.",
        "",
        "[github_portfolio_control]",
        f'profile = "{PROFILE_ID}"',
        f'candidate_commit = "{pin["candidate_commit"]}"',
        f'candidate_source_path = "{pin["candidate_source_path"]}"',
        "agents = [" + ", ".join(f'"{role}"' for role in CODEX_ROLES) + "]",
        'alias_resolution = "ALIAS_ONLY"',
        "",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# generated JSON authorities
# ---------------------------------------------------------------------------


def build_profile_binding(profile_doc: dict[str, Any]) -> dict[str, Any]:
    return {
        "schema": BINDING_DOC_SCHEMA,
        "profile": profile_doc["profile"],
        "profile_sha256": sha256(canonical(profile_doc)),
        "skills": list(profile_doc["skills"]),
        "runtime_capabilities": profile_doc["runtime_capabilities"],
        "authority": profile_doc["authority"],
        "subject_pin": profile_doc["subject_pin"],
    }


def build_requirements(skills: list[str]) -> dict[str, Any]:
    return {
        "schema": REQUIREMENTS_SCHEMA,
        "binding": PROFILE_ID,
        "shared": sorted(skills),
        "repo_owned": [],
        "surfaces": {"claude": ".claude/skills", "codex": ".agents/skills"},
        "egress": {"policy": "DENY_BY_DEFAULT", "allowed_hosts": []},
    }


def build_binding(
    repository_url_value: str, shared_commit: str, shared_tree: str, pin: dict[str, str],
    skills: list[str], shared_root: Path, requirements: dict[str, Any],
    codex_texts: dict[str, tuple[str, str, str]],
) -> dict[str, Any]:
    rows = [
        {
            "name": name, "content_sha256": content_sha256(shared_root / "skills" / name),
            "entrypoint": f"skills/{name}/SKILL.md",
        }
        for name in sorted(skills)
    ]
    codex_rows = [
        {"role": role, "template_path": codex_texts[role][1], "template_git_blob": codex_texts[role][2]}
        for role in CODEX_ROLES
    ]
    binding = {
        "schema": BINDING_SCHEMA,
        "binding": PROFILE_ID,
        "source": {"repository": repository_url_value, "commit": shared_commit, "tree": shared_tree},
        "pinned_subject": pin,
        "requirements_sha256": sha256(json_text(requirements).encode("utf-8")),
        "skills": rows,
        "codex_agents": codex_rows,
        "repo_owned": [],
        "surfaces": requirements["surfaces"],
    }
    binding["content_sha256"] = sha256(canonical(binding))
    return binding


def build_stub(kind: str, consumer_commit: str, consumer_tree: str) -> dict[str, Any]:
    doc: dict[str, Any] = {
        "schema": STUB_SCHEMA,
        "kind": kind,
        "epoch_subject": {"main_commit": consumer_commit, "tree": consumer_tree},
        "items": [],
    }
    doc["digest"] = sha256(canonical(doc))
    return doc


def verify_stub_static(path: Path, kind: str) -> None:
    if not path.is_file() or path.is_symlink():
        raise BootstrapError(f"portfolio stub missing or non-regular: {path}")
    doc = read_json(path)
    if doc.get("schema") != STUB_SCHEMA or doc.get("kind") != kind:
        raise BootstrapError(f"portfolio stub schema/kind drifted: {path}")
    if doc.get("items") != []:
        raise BootstrapError(f"portfolio stub is no longer an empty bootstrap stub: {path}")
    epoch = doc.get("epoch_subject")
    if (
        not isinstance(epoch, dict) or set(epoch) != {"main_commit", "tree"}
        or not HEX40.fullmatch(str(epoch.get("main_commit"))) or not HEX40.fullmatch(str(epoch.get("tree")))
    ):
        raise BootstrapError(f"portfolio stub epoch_subject is invalid: {path}")
    unsigned = dict(doc)
    claimed = unsigned.pop("digest", None)
    if claimed != sha256(canonical(unsigned)):
        raise BootstrapError(f"portfolio stub digest is stale: {path}")


# ---------------------------------------------------------------------------
# canonical-body-copy refusal
# ---------------------------------------------------------------------------


def assert_no_canonical_body_copied(shared_root: Path, skills: list[str], texts: dict[str, str]) -> None:
    bodies: dict[str, str] = {}
    for name in skills:
        path = shared_root / "skills" / name / "SKILL.md"
        if path.is_file():
            bodies[f"skills/{name}/SKILL.md"] = path.read_text(encoding="utf-8")
    for relative in ("skills/github-portfolio-control/AGENTS.md", "skills/github-portfolio-control/README.md"):
        path = shared_root / relative
        if path.is_file():
            bodies[relative] = path.read_text(encoding="utf-8")
    for generated_path, text in texts.items():
        for body_path, body_text in bodies.items():
            if body_text and body_text in text:
                raise BootstrapError(
                    f"generated {generated_path} embeds canonical body bytes copied from {body_path}"
                )


# ---------------------------------------------------------------------------
# receipt
# ---------------------------------------------------------------------------


def expected_evidence() -> dict[str, str]:
    return {
        "route_scaffold": "PASS",
        "immutable_source_binding": "PASS",
        "portfolio_stub_seeding": "PASS",
        "codex_agent_generation": "PASS",
        "byte_readback": "PASS",
        "hosted_evidence": "NOT_EXERCISED",
        "host_skill_discovery": "NOT_EXERCISED",
        "agent_runtime_execution": "NOT_EXERCISED",
        "provider_execution": "NOT_EXERCISED",
        "merge": "HUMAN_ADMIT_REQUIRED",
        "release": "HUMAN_ADMIT_REQUIRED",
        "rollback_execution": "NOT_EXERCISED",
    }


def artifact_records(consumer: Path, blocks: dict[Path, str], full_paths: list[Path]) -> list[dict[str, str]]:
    records: list[dict[str, str]] = []
    for relative in blocks:
        observed = observed_block(consumer / relative, GHPC_BEGIN, GHPC_END)
        records.append({
            "path": relative.as_posix(), "managed_block_sha256": sha256(observed.encode("utf-8")),
            "state": "MANAGED_BLOCK",
        })
    for relative in full_paths:
        path = consumer / relative
        if not path.is_file() or path.is_symlink():
            raise BootstrapError(f"generated artifact missing or non-regular: {relative}")
        records.append({"path": relative.as_posix(), "sha256": sha256(path.read_bytes()), "state": "GENERATED"})
    return sorted(records, key=lambda row: row["path"])


def build_ghpc_receipt(
    repository_id: str, repository_url_value: str, shared_commit: str, shared_tree: str,
    pin: dict[str, str], rollback: dict[str, str], artifacts: list[dict[str, str]],
    binding: dict[str, Any], profile_doc: dict[str, Any],
) -> dict[str, Any]:
    subject = {
        "consumer_repository": repository_id, "rollback": rollback,
        "shared_commit": shared_commit, "shared_tree": shared_tree, "artifacts": artifacts,
    }
    receipt: dict[str, Any] = {
        "schema": GHPC_RECEIPT_SCHEMA,
        "consumer": {
            "repository": repository_id, "generated_subject_sha256": sha256(canonical(subject)),
        },
        "shared_subject": {
            "repository": repository_url_value, "commit": shared_commit, "tree": shared_tree,
            "pinned_main_commit": pin["main_commit"],
            "pinned_owned_tree_path": pin["owned_tree_path"],
            "pinned_owned_tree": pin["owned_tree"],
            "pinned_candidate_commit": pin["candidate_commit"],
            "pinned_candidate_source_path": pin["candidate_source_path"],
        },
        "profile": {
            "id": profile_doc["profile"], "sha256": sha256(canonical(profile_doc)),
            "skills": list(profile_doc["skills"]),
        },
        "binding": {
            "path": GHPC_BINDING_REL.as_posix(), "semantic_sha256": sha256(canonical(binding)),
            "content_sha256": binding["content_sha256"],
        },
        "artifacts": artifacts,
        "evidence": expected_evidence(),
        "authority": {
            "automatic_merge": False, "automatic_conflict_resolution": False,
            "visibility_change": False, "credential_values": False,
            "provider_activation": False, "production_writeback": False,
        },
        "rollback": rollback,
        "decision_record_policy": "OBSERVATIONS_AND_DECISIONS_ONLY",
    }
    receipt["receipt_sha256"] = sha256(canonical(receipt))
    return receipt


def validate_ghpc_receipt_shape(receipt: dict[str, Any]) -> None:
    required = {
        "schema", "consumer", "shared_subject", "profile", "binding", "artifacts",
        "evidence", "authority", "rollback", "decision_record_policy", "receipt_sha256",
    }
    if set(receipt) != required or receipt.get("schema") != GHPC_RECEIPT_SCHEMA:
        raise BootstrapError("ghpc bootstrap receipt schema or fields drifted")
    reject_unsafe(receipt)
    unsigned = dict(receipt)
    claimed = unsigned.pop("receipt_sha256", None)
    if claimed != sha256(canonical(unsigned)):
        raise BootstrapError("ghpc bootstrap receipt self digest is stale")
    if receipt.get("decision_record_policy") != "OBSERVATIONS_AND_DECISIONS_ONLY":
        raise BootstrapError("ghpc bootstrap receipt attempted to persist private reasoning")
    authority = receipt.get("authority")
    if not isinstance(authority, dict) or not authority or any(v is not False for v in authority.values()):
        raise BootstrapError("ghpc bootstrap receipt widened automatic authority")
    if receipt.get("evidence") != expected_evidence():
        raise BootstrapError("ghpc bootstrap receipt promoted an unexercised or Human-owned lane")
    rollback = receipt.get("rollback")
    if not isinstance(rollback, dict) or set(rollback) != {"commit", "tree"}:
        raise BootstrapError("ghpc bootstrap receipt rollback subject is absent")
    if not HEX40.fullmatch(rollback["commit"]) or not HEX40.fullmatch(rollback["tree"]):
        raise BootstrapError("ghpc bootstrap receipt rollback identity is mutable")


def validate_ghpc_receipt(consumer: Path, expected: dict[str, Any]) -> None:
    path = consumer / GHPC_RECEIPT_REL
    if not path.is_file() or path.is_symlink():
        raise BootstrapError("ghpc bootstrap receipt missing or non-regular")
    observed = read_json(path)
    validate_ghpc_receipt_shape(observed)
    validate_rollback(consumer, observed["rollback"])
    if observed != expected:
        raise BootstrapError("ghpc bootstrap receipt is stale or substituted")
    for row in observed["artifacts"]:
        relative = row["path"]
        artifact = consumer / relative
        if not artifact.is_file() or artifact.is_symlink():
            raise BootstrapError(f"ghpc bootstrap receipt artifact is stale: {relative}")
        if row["state"] == "MANAGED_BLOCK":
            observed_digest = sha256(observed_block(artifact, GHPC_BEGIN, GHPC_END).encode("utf-8"))
        else:
            observed_digest = sha256(artifact.read_bytes())
        expected_digest = row.get("managed_block_sha256") or row.get("sha256")
        if observed_digest != expected_digest:
            raise BootstrapError(f"ghpc bootstrap receipt artifact is stale: {relative}")


def rollback_subject(consumer: Path, initial_commit: str, initial_tree: str) -> dict[str, str]:
    receipt_path = consumer / GHPC_RECEIPT_REL
    if not receipt_path.is_file():
        return {"commit": initial_commit, "tree": initial_tree}
    receipt = read_json(receipt_path)
    validate_ghpc_receipt_shape(receipt)
    validate_rollback(consumer, receipt["rollback"])
    return receipt["rollback"]


def preflight(consumer: Path) -> None:
    preflight_generated(consumer / GHPC_PROFILE_REL, {BINDING_DOC_SCHEMA})
    preflight_generated(consumer / GHPC_REQUIREMENTS_REL, {REQUIREMENTS_SCHEMA})
    preflight_generated(consumer / GHPC_BINDING_REL, {BINDING_SCHEMA})
    preflight_generated(consumer / GHPC_RECEIPT_REL, {GHPC_RECEIPT_SCHEMA})
    for relative in PORTFOLIO_STUB_RELS.values():
        preflight_generated(consumer / relative, {STUB_SCHEMA})
    preflight_generated(consumer / CODEX_CONFIG_REL, marker=CODEX_MARKER)
    for role in CODEX_ROLES:
        preflight_generated(consumer / codex_agent_rel(role), marker=CODEX_MARKER)


# ---------------------------------------------------------------------------
# orchestration
# ---------------------------------------------------------------------------


def bootstrap_consumer_ghpc(
    *, consumer: Path, repository_id: str, profile_path: Path, apply: bool,
    shared_root: Path = SHARED_ROOT,
) -> None:
    if not REPOSITORY_ID.fullmatch(repository_id):
        raise BootstrapError("repository-id must be owner/name")
    consumer = consumer.resolve()
    initial_commit, initial_tree = ensure_git_worktree(consumer)

    profile_doc = ghpc_profile_document(profile_path)
    pin = profile_doc["subject_pin"]
    skills = list(profile_doc["skills"])
    shared_commit, shared_tree = validate_subject_pin(shared_root, pin)
    repository_url_value = repository_url(shared_root)

    blocks = ghpc_route_blocks(repository_id)
    requirements = build_requirements(skills)
    profile_binding = build_profile_binding(profile_doc)
    codex_texts = codex_agent_texts(shared_root, pin)
    config_text = codex_config_text(pin)
    full_paths = [
        GHPC_PROFILE_REL, GHPC_REQUIREMENTS_REL, GHPC_BINDING_REL,
        *PORTFOLIO_STUB_RELS.values(), CODEX_CONFIG_REL,
        *(codex_agent_rel(role) for role in CODEX_ROLES),
    ]

    preflight(consumer)
    reject_copied_skill_bodies(consumer, skills)

    if apply:
        rollback = rollback_subject(consumer, initial_commit, initial_tree)
        snapshot = capture(consumer, generated_paths())
        try:
            apply_routes(consumer, blocks)
            write_full(consumer, GHPC_PROFILE_REL, json_text(profile_binding))
            write_full(consumer, GHPC_REQUIREMENTS_REL, json_text(requirements))
            binding = build_binding(
                repository_url_value, shared_commit, shared_tree, pin, skills, shared_root,
                requirements, codex_texts,
            )
            write_full(consumer, GHPC_BINDING_REL, json_text(binding))

            stub_commit = git_out(consumer, "rev-parse", "HEAD")
            stub_tree = git_out(consumer, "rev-parse", "HEAD^{tree}")
            for kind, relative in PORTFOLIO_STUB_RELS.items():
                write_full(consumer, relative, json_text(build_stub(kind, stub_commit, stub_tree)))

            write_full(consumer, CODEX_CONFIG_REL, config_text)
            for role in CODEX_ROLES:
                write_full(consumer, codex_agent_rel(role), codex_texts[role][0])

            generated_texts = {
                p.as_posix(): (consumer / p).read_text(encoding="utf-8") for p in (*blocks, *full_paths)
            }
            assert_no_canonical_body_copied(shared_root, skills, generated_texts)

            artifacts = artifact_records(consumer, blocks, full_paths)
            receipt = build_ghpc_receipt(
                repository_id, repository_url_value, shared_commit, shared_tree, pin,
                rollback, artifacts, binding, profile_doc,
            )
            write_full(consumer, GHPC_RECEIPT_REL, json_text(receipt))
            validate_ghpc_receipt(consumer, receipt)
        except Exception:
            restore(consumer, snapshot)
            raise
    else:
        check_routes(consumer, blocks)
        check_full(consumer, GHPC_PROFILE_REL, json_text(profile_binding))
        check_full(consumer, GHPC_REQUIREMENTS_REL, json_text(requirements))
        binding = build_binding(
            repository_url_value, shared_commit, shared_tree, pin, skills, shared_root,
            requirements, codex_texts,
        )
        check_full(consumer, GHPC_BINDING_REL, json_text(binding))
        for kind, relative in PORTFOLIO_STUB_RELS.items():
            verify_stub_static(consumer / relative, kind)
        check_full(consumer, CODEX_CONFIG_REL, config_text)
        for role in CODEX_ROLES:
            check_full(consumer, codex_agent_rel(role), codex_texts[role][0])

        generated_texts = {
            p.as_posix(): (consumer / p).read_text(encoding="utf-8") for p in (*blocks, *full_paths)
        }
        assert_no_canonical_body_copied(shared_root, skills, generated_texts)

        existing = read_json(consumer / GHPC_RECEIPT_REL)
        validate_ghpc_receipt_shape(existing)
        validate_rollback(consumer, existing["rollback"])
        artifacts = artifact_records(consumer, blocks, full_paths)
        expected = build_ghpc_receipt(
            repository_id, repository_url_value, shared_commit, shared_tree, pin,
            existing["rollback"], artifacts, binding, profile_doc,
        )
        validate_ghpc_receipt(consumer, expected)

    print(
        "GHPC-BOOTSTRAP-GREEN "
        f"consumer={repository_id} shared={shared_commit[:12]} routes={len(blocks)} "
        f"mode={'apply' if apply else 'check'} hosted_evidence=NOT_EXERCISED "
        "merge=HUMAN_ADMIT_REQUIRED"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--consumer", required=True, type=Path)
    parser.add_argument("--repository-id", required=True)
    parser.add_argument("--profile", type=Path, default=PROFILE_SOURCE_GHPC)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--apply", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    profile = args.profile if args.profile.is_absolute() else SHARED_ROOT / args.profile
    try:
        bootstrap_consumer_ghpc(
            consumer=args.consumer, repository_id=args.repository_id,
            profile_path=profile, apply=args.apply,
        )
        return 0
    except BootstrapError as exc:
        print(f"GHPC-BOOTSTRAP-RED {exc}", file=sys.stderr)
        return 2
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        print(f"GHPC-BOOTSTRAP-INVALID {exc}", file=sys.stderr)
        return 64


if __name__ == "__main__":
    raise SystemExit(main())
