#!/usr/bin/env python3
"""Thin, exact-subject CADG + Domain Decoupling bootstrap for a new repository."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import subprocess
import sys
from typing import Any

from consumer_bootstrap_common import (
    BootstrapError, REPOSITORY_ID, capture, ensure_git_worktree, file_identity,
    git_out, json_text, read_json, reject_copied_skill_bodies, restore,
    sha256,
)

SHARED_ROOT = Path(__file__).resolve().parents[3]
PROFILE_SOURCE = Path("skills/shared-skills-infra/references/repository-control-plane-profile.cadg.json")
WORKFLOW_ADAPTER = Path("skills/shared-skills-infra/modules/github-actions-consumer-bootstrap-cadg.yml")
PACKET_SCHEMA = Path("skills/human-led-agentic-engineering/references/cadg/cadg-packet.schema.json")
CHECKER = Path("skills/human-led-agentic-engineering/modules/github-pr-cadg/cadg_pr_admission.py")
REGISTRY = Path("registry.json")

PROFILE_REL = Path(".agents/control-plane/profiles/cadg.json")
REQUIREMENTS_REL = Path(".agents/control-plane/requirements/cadg.json")
SOURCE_REL = Path(".agents/cadg/source.json")
BINDING_REL = Path(".agents/cadg/binding.json")
RECEIPT_REL = Path(".agents/cadg/receipt.json")
WORKFLOW_REL = Path(".github/workflows/cadg-pr-admission.yml")
ROUTE_RELS = (
    Path(".agents/cadg/README.md"),
    Path(".agents/cadg/packets/README.md"),
    Path(".agents/cadg/receipts/README.md"),
    Path(".agents/cadg/shadow/README.md"),
    Path(".agents/cadg/history/README.md"),
    Path("docs/traceability/CADG_INDEX.md"),
)

SOURCE_SCHEMA = "shared-skills/cadg-source-pin/v1"
BINDING_SCHEMA = "shared-skills/cadg-binding/v1"
RECEIPT_SCHEMA = "shared-skills/cadg-bootstrap-receipt/v1"
PROFILE_BINDING_SCHEMA = "repository-control-plane-binding-cadg/v1"
REQUIREMENTS_SCHEMA = "shared-skills/consumer-requirements/v1"
MARKER = "<!-- GENERATED BY CADG CONSUMER BOOTSTRAP -->"
WORKFLOW_MARKER = "# GENERATED BY CADG CONSUMER BOOTSTRAP"

EXPECTED_SKILLS = [
    "shared-skills-infra",
    "human-led-agentic-engineering",
    "procedural-shadow-runtime",
    "spatial-loop-systems-engineering",
    "agentic-tech-lead-orchestration",
    "git-town-stacked-pr-worker",
    "github-delivery-loop",
]


def canonical(value: Any) -> bytes:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode()


def repository_url(root: Path) -> str:
    remotes = set(git_out(root, "remote").splitlines())
    for name in ("github", "origin", "github-archive"):
        if name not in remotes:
            continue
        value = git_out(root, "remote", "get-url", name).removesuffix(".git")
        if value.startswith("git@") and ":" in value:
            host, path = value[4:].split(":", 1)
            value = f"https://{host}/{path}"
        if value.startswith("https://") and "@" not in value.split("://", 1)[1].split("/", 1)[0]:
            return value
    raise BootstrapError("skills-shared requires a credential-free HTTPS remote")


def skill_digest(root: Path, name: str) -> str:
    skill = root / "skills" / name
    if not (skill / "SKILL.md").is_file():
        raise BootstrapError(f"canonical shared Skill missing: {name}")
    digest = hashlib.sha256()
    for file in sorted(p for p in skill.rglob("*") if p.is_file() and "__pycache__" not in p.parts):
        digest.update(file.relative_to(skill).as_posix().encode())
        digest.update(b"\0")
        digest.update(file.read_bytes())
        digest.update(b"\0")
    return digest.hexdigest()


def profile_document(shared_root: Path) -> dict[str, Any]:
    value = read_json(shared_root / PROFILE_SOURCE)
    if value.get("schema") != "repository-control-plane-profile/v1" or value.get("profile") != "cadg-domain-decoupling":
        raise BootstrapError("unsupported CADG profile")
    if value.get("skills") != EXPECTED_SKILLS:
        raise BootstrapError("CADG profile Skill closure/order drifted")
    cadg = value.get("cadg")
    if not isinstance(cadg, dict) or cadg.get("default_mode") != "OBSERVE":
        raise BootstrapError("CADG profile must default to OBSERVE")
    if cadg.get("allowed_modes") != ["OBSERVE", "WARN", "GATE"]:
        raise BootstrapError("CADG mode vocabulary drifted")
    authority = value.get("authority")
    if not isinstance(authority, dict) or not authority or any(v is not False for v in authority.values()):
        raise BootstrapError("CADG profile widened automatic authority")
    registry = read_json(shared_root / REGISTRY)
    admitted = {row.get("name") for row in registry.get("shared", []) if isinstance(row, dict)}
    missing = [name for name in EXPECTED_SKILLS if name not in admitted]
    if missing:
        raise BootstrapError("CADG profile references unregistered shared Skills: " + ", ".join(missing))
    return value


def source_document(shared_root: Path) -> dict[str, Any]:
    if git_out(shared_root, "status", "--porcelain", "--untracked-files=all"):
        raise BootstrapError("skills-shared source must be clean")
    commit = git_out(shared_root, "rev-parse", "HEAD")
    tree = git_out(shared_root, "rev-parse", "HEAD^{tree}")
    artifacts: dict[str, dict[str, str]] = {}
    for key, path in {
        "profile": PROFILE_SOURCE,
        "workflow_adapter": WORKFLOW_ADAPTER,
        "packet_schema": PACKET_SCHEMA,
        "checker": CHECKER,
    }.items():
        blob, digest = file_identity(shared_root, path)
        artifacts[key] = {"path": path.as_posix(), "git_blob": blob, "sha256": digest}
    return {
        "schema": SOURCE_SCHEMA,
        "repository": repository_url(shared_root),
        "commit": commit,
        "tree": tree,
        "artifacts": artifacts,
    }


def requirements(profile: dict[str, Any]) -> dict[str, Any]:
    return {
        "schema": REQUIREMENTS_SCHEMA,
        "binding": "cadg-domain-decoupling",
        "shared": list(profile["skills"]),
        "repo_owned": [],
        "surfaces": {"claude": ".claude/skills", "codex": ".agents/skills"},
    }


def binding_document(shared_root: Path, source: dict[str, Any], profile: dict[str, Any]) -> dict[str, Any]:
    return {
        "schema": BINDING_SCHEMA,
        "source": {"repository": source["repository"], "commit": source["commit"], "tree": source["tree"]},
        "profile": "cadg-domain-decoupling",
        "profile_sha256": sha256(canonical(profile)),
        "mode": "OBSERVE",
        "skills": [{"name": name, "content_sha256": skill_digest(shared_root, name)} for name in profile["skills"]],
        "cadg": {
            "packet_schema": source["artifacts"]["packet_schema"],
            "checker": source["artifacts"]["checker"],
            "reconstructed_history": "NOT_ORIGINAL_REASONING",
        },
        "evidence_ceiling": {
            "bootstrap": "VERIFIED_DETERMINISTIC_BOOTSTRAP",
            "agent_execution": "NOT_EXERCISED",
            "independent_shadow": "NOT_EXERCISED",
            "merge_release": "HUMAN_ADMIT_REQUIRED",
        },
        "authority": profile["authority"],
    }


def profile_binding(profile: dict[str, Any]) -> dict[str, Any]:
    return {
        "schema": PROFILE_BINDING_SCHEMA,
        "profile": profile["profile"],
        "profile_sha256": sha256(canonical(profile)),
        "mode": profile["cadg"]["default_mode"],
        "skills": profile["skills"],
        "authority": profile["authority"],
    }


def route_text(repository_id: str) -> dict[Path, str]:
    common = (
        f"{MARKER}\n"
        f"Repository: `{repository_id}`. CADG is a thin causal-observability binding to immutable skills-shared subjects.\n\n"
        "CTX -> ASM -> DEC -> DELTA -> EV is provenance, not a scheduler dependency and not G8.\n"
        "Reconstructed history records OBSERVED/DERIVED/INFERRED evidence and is never original private reasoning.\n"
        "Authoritative packet/checker identities are in `.agents/cadg/source.json`; generated artifacts must not copy canonical Skill bodies.\n"
        "Bootstrap PASS does not prove Agent execution, independent Shadow, merge, release, or production.\n"
    )
    return {
        Path(".agents/cadg/README.md"): common + "\nUse `packets/`, `receipts/`, `shadow/`, and `history/` as typed artifact routes.\n",
        Path(".agents/cadg/packets/README.md"): f"{MARKER}\nCADG packet route. Packet schema is content-bound in `../source.json`.\n",
        Path(".agents/cadg/receipts/README.md"): f"{MARKER}\nDeterministic/live/Human receipts remain separate evidence lanes.\n",
        Path(".agents/cadg/shadow/README.md"): f"{MARKER}\nIndependent Shadow receipts live here; directory presence is NOT_EXERCISED.\n",
        Path(".agents/cadg/history/README.md"): f"{MARKER}\nHistorical reconstructions are labelled RECONSTRUCTED_HISTORY, never original reasoning.\n",
        Path("docs/traceability/CADG_INDEX.md"): common + "\nGeneric learning belongs upstream in skills-shared; repository facts stay consumer-owned.\n",
    }


def workflow_text(shared_root: Path, source: dict[str, Any]) -> str:
    template = (shared_root / WORKFLOW_ADAPTER).read_text(encoding="utf-8")
    return template.replace("__SHARED_REPOSITORY__", source["repository"] + ".git").replace("__SHARED_COMMIT__", source["commit"])


def generated_paths() -> set[Path]:
    return set(ROUTE_RELS) | {PROFILE_REL, REQUIREMENTS_REL, SOURCE_REL, BINDING_REL, RECEIPT_REL, WORKFLOW_REL}


def expected_without_receipt(shared_root: Path, repository_id: str) -> tuple[dict[Path, str], dict[str, Any], dict[str, Any], dict[str, Any]]:
    profile = profile_document(shared_root)
    source = source_document(shared_root)
    binding = binding_document(shared_root, source, profile)
    texts = route_text(repository_id)
    texts[PROFILE_REL] = json_text(profile_binding(profile))
    texts[REQUIREMENTS_REL] = json_text(requirements(profile))
    texts[SOURCE_REL] = json_text(source)
    texts[BINDING_REL] = json_text(binding)
    texts[WORKFLOW_REL] = workflow_text(shared_root, source)
    return texts, profile, source, binding


def receipt_document(repository_id: str, consumer_commit: str, consumer_tree: str, texts: dict[Path, str], source: dict[str, Any]) -> dict[str, Any]:
    artifacts = [
        {"path": path.as_posix(), "sha256": sha256(text.encode("utf-8"))}
        for path, text in sorted(texts.items(), key=lambda item: item[0].as_posix())
    ]
    return {
        "schema": RECEIPT_SCHEMA,
        "repository": repository_id,
        "shared_subject": {"commit": source["commit"], "tree": source["tree"]},
        "consumer_subject_before_bootstrap": {"commit": consumer_commit, "tree": consumer_tree},
        "artifacts": artifacts,
        "rollback": {"mode": "DELETE_GENERATED_PROFILE", "requires_exact_artifact_hashes": True},
        "states": {
            "bootstrap": "VERIFIED_DETERMINISTIC_BOOTSTRAP",
            "agent_execution": "NOT_EXERCISED",
            "independent_shadow": "NOT_EXERCISED",
            "merge_release": "HUMAN_ADMIT_REQUIRED",
        },
    }


def reject_unmanaged_existing(consumer: Path, expected: dict[Path, str]) -> None:
    for path, text in expected.items():
        target = consumer / path
        if target.is_symlink() or (target.exists() and not target.is_file()):
            raise BootstrapError(f"generated target is not a regular file: {path}")
        if target.is_file() and target.read_text(encoding="utf-8") != text:
            raise BootstrapError(f"refuse to overwrite human/unknown generated file: {path}")


def validate_exact(consumer: Path, expected: dict[Path, str], receipt: dict[str, Any], skills: list[str]) -> None:
    for path, text in expected.items():
        target = consumer / path
        if not target.is_file() or target.is_symlink() or target.read_text(encoding="utf-8") != text:
            raise BootstrapError(f"generated CADG artifact missing or drifted: {path}")
    reject_copied_skill_bodies(consumer, skills)
    observed_receipt = read_json(consumer / RECEIPT_REL)
    if observed_receipt != receipt:
        raise BootstrapError("CADG bootstrap receipt missing or drifted")
    if observed_receipt["states"] != {
        "bootstrap": "VERIFIED_DETERMINISTIC_BOOTSTRAP",
        "agent_execution": "NOT_EXERCISED",
        "independent_shadow": "NOT_EXERCISED",
        "merge_release": "HUMAN_ADMIT_REQUIRED",
    }:
        raise BootstrapError("bootstrap evidence was promoted to a later lane")


def bootstrap(*, consumer: Path, repository_id: str, apply: bool, rollback: bool = False, shared_root: Path = SHARED_ROOT, fail_after: int | None = None) -> None:
    if not REPOSITORY_ID.fullmatch(repository_id):
        raise BootstrapError("repository-id must be owner/name")
    consumer = consumer.resolve()
    consumer_commit, consumer_tree = ensure_git_worktree(consumer)
    texts, profile, source, _binding = expected_without_receipt(shared_root, repository_id)
    receipt = receipt_document(repository_id, consumer_commit, consumer_tree, texts, source)
    reject_copied_skill_bodies(consumer, profile["skills"])

    if rollback:
        observed = read_json(consumer / RECEIPT_REL)
        if observed != receipt:
            raise BootstrapError("rollback requires exact current CADG receipt and subject")
        validate_exact(consumer, texts, receipt, profile["skills"])
        for relative in sorted(generated_paths(), key=lambda p: len(p.parts), reverse=True):
            path = consumer / relative
            if path.is_file() or path.is_symlink():
                path.unlink()
        for parent in sorted({(consumer / p).parent for p in generated_paths()}, key=lambda p: len(p.parts), reverse=True):
            current = parent
            while current != consumer and current.is_dir():
                try:
                    current.rmdir()
                except OSError:
                    break
                current = current.parent
        print(f"CADG-BOOTSTRAP-ROLLED-BACK consumer={repository_id}")
        return

    if not apply:
        validate_exact(consumer, texts, receipt, profile["skills"])
        print(f"CADG-BOOTSTRAP-GREEN consumer={repository_id} shared={source['commit'][:12]} mode=check agent=NOT_EXERCISED shadow=NOT_EXERCISED")
        return

    reject_unmanaged_existing(consumer, texts)
    snapshot = capture(consumer, generated_paths())
    try:
        count = 0
        for relative, text in sorted(texts.items(), key=lambda item: item[0].as_posix()):
            target = consumer / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(text, encoding="utf-8")
            count += 1
            if fail_after is not None and count >= fail_after:
                raise BootstrapError("injected downstream failure")
        (consumer / RECEIPT_REL).write_text(json_text(receipt), encoding="utf-8")
        validate_exact(consumer, texts, receipt, profile["skills"])
    except Exception:
        restore(consumer, snapshot)
        raise
    print(f"CADG-BOOTSTRAP-GREEN consumer={repository_id} shared={source['commit'][:12]} mode=apply agent=NOT_EXERCISED shadow=NOT_EXERCISED")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--consumer", required=True, type=Path)
    parser.add_argument("--repository-id", required=True)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--apply", action="store_true")
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--rollback", action="store_true")
    args = parser.parse_args(argv)
    try:
        bootstrap(consumer=args.consumer, repository_id=args.repository_id, apply=args.apply, rollback=args.rollback)
        return 0
    except BootstrapError as exc:
        print(f"CADG-BOOTSTRAP-RED {exc}", file=sys.stderr)
        return 2
    except (OSError, UnicodeError, json.JSONDecodeError, subprocess.SubprocessError) as exc:
        print(f"CADG-BOOTSTRAP-INVALID {exc}", file=sys.stderr)
        return 64


if __name__ == "__main__":
    raise SystemExit(main())
